### ISSUE TITLE
google login

### ISSUE THREAD

**Issue by Tsunamii** [BrianEstrada/PokeScanner#10]
Having a google login as an alternative to the ptc login would be really handy since most of the time its only the ptc login that causes the problems.
I don't know if the java api already supports the google login but if it does it shouldn't be too hard to add :)

**Comment by BrianEstrada** [comment]
I'll be adding it over the weekend :)

**Comment by BrianEstrada** [comment]
#23

**Comment by GaelicGamer** [comment]
O didn't see this already open, are you already working this Brian?  If so I'll move on to a different issue.

**Comment by BrianEstrada** [comment]
@GaelicGamer Go ahead and work on it! Whats your email? I'll invite you to the slack channel

**Comment by GaelicGamer** [comment]
noah.castro.hart@gmail.com  I'm trying to adapt the auth methods from the
python api to see if that goes anywhere, hopefully it does.

Regards,
Noah

**Comment by BrianEstrada** [comment]
@GaelicGamer Invited you!

**Comment by BrianEstrada** [comment]
Added

**Comment by GaelicGamer** [comment]
O damn, beat me to it, going to go ahead and pull and see how you went about it.
