### ISSUE TITLE
Link to register for PTC on login screen

### ISSUE THREAD

**Issue by nabakin** [BrianEstrada/PokeScanner#101]
A lot of people don't know where to create a new PTC account (here: https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin).

It would be convenient if there is a simple link on the login screen.

**Comment by BrianEstrada** [comment]
I don't think this is an issue anymore (plus I don't want to break a TOS)
