### ISSUE TITLE
Directions Feature

### ISSUE THREAD

**Issue by Hoully111** [BrianEstrada/PokeScanner#102]
Will this feature only work with Google GPS or can it work in other GPS apps reason i ask is my google gps hates me and the second i start navigation it auto loops back to directions

Just inquiring if the navigate feature will open to default GPS application

**Comment by BrianEstrada** [comment]
@Hoully111 This is actually a really good suggestion and I will definately add this to the next release

**Comment by Hoully111** [comment]
Ty because ive searched and searched and can't fix Google Maps so being able to use an alternative application would be great

**Comment by Hoully111** [comment]
Save me from a factory reset LOL

**Comment by Hoully111** [comment]
Fixed it :)
