### ISSUE TITLE
save password(s) and gps tracking.

### ISSUE THREAD

**Issue by phantomguy** [BrianEstrada/PokeScanner#104]
Sometimes the app crashes and it logs you out, and you have to re-type the password. is it possible to save the password (or multiple of them, in case you have a google login as well).

Just a notion about gps tracking it's really inconvenient if you're using gps tracking and you want to scan somewhere else. You have to go to settings and turn the gps off, go back to the program, scan a far away place, go back to settings, turn gps on, and continue with gps tracing. Because it recenters gps as soon as you start tracking.

**Comment by BrianEstrada** [comment]
you can just keep GPS tracking off and use the icon to the top right to go to your location and scan there :P

**Comment by phantomguy** [comment]
How about just saving the (last) password in the txt box? or is that part of the complicated code? (i have no idea)

**Comment by BrianEstrada** [comment]
I'm pretty sure it should be automatically entered but I'll check whats going on...the real issue here is what are you doing before you're crashing? do you get any sort of error?

**Comment by phantomguy** [comment]
in version 1.6.1 (was force closing), but in the newest one (.5) if i close the app myself and open it again, it somtimes has no pass (just username) entered.

**Comment by BrianEstrada** [comment]
I found the issue hehehe it should be working for the 1.7.0 release

**Comment by BrianEstrada** [comment]
Check out the subreddit for the alpha verrsion @phantomguy
