### ISSUE TITLE
app crashes when resumed from task switch

### ISSUE THREAD

**Issue by someguy235** [BrianEstrada/PokeScanner#107]
I'm getting consistent crashes ("Unfortunately PokeScanner has stopped") when switching back to this app after using other applications. It doesn't always happen, but I can reliably reproduce it by switching to a resource-intensive application (like Pokemon GO) and back. I wasn't seeing this until about a day ago. This is on a Nexus 5x.

**Comment by BrianEstrada** [comment]
What version are you on?

**Comment by someguy235** [comment]
1.6.5

**Comment by BrianEstrada** [comment]
This should be fixed in 1.7.0 but is untested please let me know if the issue is fixed!
