### ISSUE TITLE
Scan Overlay

### ISSUE THREAD

**Issue by jnovack** [BrianEstrada/PokeScanner#11]
Do you get back coordinates for your scanning locations?  

Is it possible to add a rectangle with the area it scanned at like 5% transparency so we know what is in our search radius (and whether can shrink or enlarge it for our needs)?

Do I need a 5 Search Radius?  Dunno.  Do I need a 6?? 

https://developers.google.com/maps/documentation/javascript/shapes#rectangles

**Comment by guipenedo** [comment]
You do realize you just linked JAVASCRIPT documentation right? JAVA != JAVASCRIPT

**Comment by BrianEstrada** [comment]
yeah this is apart of the next release stay tuned tonight :)

**Comment by jnovack** [comment]
Yep, I realize. Had I found JAVA documentation, I would have linked it.  However, the JAVASCRIPT documentation had visual examples, which I thought were helpful.  Considering that a number of objects are the comparable between the Android JAVA classes and browser JAVASCRIPT classes for Google Maps, I found it helpful.
