### ISSUE TITLE
Empty map, nothing's happens

### ISSUE THREAD

**Issue by Marty25** [BrianEstrada/PokeScanner#110]
Hello! I'm trying to run this app on my device (android 5.0) and getting just empty map. After scanning nothing happens. (Sorry for my english).

[http://i.imgur.com/qkFMBuT.jpg](url)

**Comment by Marty25** [comment]
Update: APK in Download Section works fine, but something is wrong with my build.

**Comment by BrianEstrada** [comment]
Ah yeah we aren't including the key to the Google Maps API anymore (Other devs are forking our project and using it on the playstore) really sorry about that you'll need to put your own key in the manifest!

**Comment by BrianEstrada** [comment]
Solved
