### ISSUE TITLE
Wrong Icon location

### ISSUE THREAD

**Issue by acidic48** [BrianEstrada/PokeScanner#112]
I'm using LG Nexus 4 and when I try the updates version 1.6.5
the gear button is location is above the compass button http://prnt.sc/bxyinl
is it a bug or the cause is from my phone?
i'm sorry for my bad english

**Comment by BrianEstrada** [comment]
Ahhh the compass icon shouldn't be showing up! I'll look into it thank you.

**Comment by acidic48** [comment]
Thanks.
BTW i figure there was the compass button when I try rotating the maps
