### ISSUE TITLE
So much lag with massive pokemons

### ISSUE THREAD

**Issue by Seguro19** [BrianEstrada/PokeScanner#113]
In some popular sites there are sooo many pokemons an the mobile phone get lagged so much, i have a Xperia Z5 with 3GB of RAM and get lagged so much, maybe because the counters of every pokemon, is there any way to solve this lag?, maybe set the counter per 30 seconds and not every second or something?

**Comment by BrianEstrada** [comment]
You can adjust the scan settings please read the settings.
