### ISSUE TITLE
Map style

### ISSUE THREAD

**Issue by akymos** [BrianEstrada/PokeScanner#116]
Add an option to switch between old and new map style

**Comment by BrianEstrada** [comment]
When you say old and new map style what exactly do you mean? sorry don't understand too well

**Comment by akymos** [comment]
Old style: 1.6.5
New style: 1.7.0 alpha
Referring to https://redd.it/4ustva

**Comment by BrianEstrada** [comment]
I'll look at this in a bit and see to merging it thanks!
