### ISSUE TITLE
Current location scan

### ISSUE THREAD

**Issue by Shagon94** [BrianEstrada/PokeScanner#117]
Currently when you opt in for gps scan you get an error "Failed to center camera"; It would be really helpful if the location is cached and be vary of gps, eg. when you're in the city just toggle on gps location and it should scan your area, and when you turn on the app a couple of hours later the location is loaded since now you have to each and every time zoom in to your country and find the location you need.

**Comment by BrianEstrada** [comment]
Issue should be fixed with the latest version! 1.7.0 Alpha
