### ISSUE TITLE
material design icon

### ISSUE THREAD

**Issue by Tsunamii** [BrianEstrada/PokeScanner#12]
tried to get as close to the guidelines as possible: [http://imgur.com/a/hk0YW](url)
in case you want something changed or need specific sizes/dpi settings i can change that in the psd without problem :)

**Comment by BrianEstrada** [comment]
This is dope! I'll be sure to add this in the next release do you mind if I credit you? (If so what do you want me to credit you under?)

**Comment by SpiderDice** [comment]
Wow! Great job! Very Instagram-esque but recognizable as a Pokédex. Love it!

**Comment by Tsunamii** [comment]
Thanks :)  
Glad you like it. Credit is fine as it is.
