### ISSUE TITLE
Use original app images as map markers

### ISSUE THREAD

**Issue by someguy235** [BrianEstrada/PokeScanner#13]
It would make the map easier to use if the Pokemon markers used the same images as the official app.

**Comment by SpiderDice** [comment]
The 3D ones?

**Comment by Darkrift411** [comment]
I have an insanely high resolution/dpi setup on my phone which works great for everything, but these icons are smaller than fleas for me. I would like slightly larger icons, however that becomes a major pain until you have filtering enabled. I would say get filtering working, and then add a new double set of icons. One small and basic and one larger more detailed. The detailed set could use the ingame images and have an option to enable them.

Btw, does the hamburger menu do anything yet or am I losing it?

**Comment by someguy235** [comment]
I was thinking of the ones in the "nearby" tracker. This project uses them: https://github.com/AHAAAAAAA/PokemonGo-Map

**Comment by SpiderDice** [comment]
@someguy235 Ahh okay. Yeah..I think those look nicer..softer..

**Comment by BrianEstrada** [comment]
@Darkrift411 it opens up a menu but that hasnt been implemented yet.

**Comment by BrianEstrada** [comment]
I'll be switching the icons soon but I want to get some functionality out first before. @SpiderDice @someguy235

**Comment by SpiderDice** [comment]
All good @BrianEstrada :+1:

**Comment by MrYawnie** [comment]
@BrianEstrada while you change the icons, could you add different sizes for different dpi? The ones you have now look super small on OnePlus 3 with 400dpi.

**Comment by BrianEstrada** [comment]
@MrYawnie Working on scaling issue right now is that it slows down the device

**Comment by Darkrift411** [comment]
/me adds the wontuse label 

Sorry, these issues make it unusable for me. Keep up the good work though.
