### ISSUE TITLE
Zoom buttons for map

### ISSUE THREAD

**Issue by zanesc** [BrianEstrada/PokeScanner#133]
This isn't urgent but it would be nice to have zoom in and out buttons for the map. I am running this app from a computer with BlueStacks and it's not possible to zoom without buttons.

**Comment by EZTEQ** [comment]
Press `Ctrl` while clicking on the map. With this combination you pinch to zoom in BlueStacks.

**Comment by zanesc** [comment]
@EZTEQ but how do you zoom back out? i've tried all different key combinations.
