### ISSUE TITLE
[Urgent] Passwords

### ISSUE THREAD

**Issue by fizzxed** [BrianEstrada/PokeScanner#134]
In the build.gradle of the latest commit, you have some passwords exposed as well as a hardcoded path
@BrianEstrada

**Comment by fizzxed** [comment]
Also there's a live key in keys.xml?

**Comment by BrianEstrada** [comment]
Jesus christ

**Comment by BrianEstrada** [comment]
Thanks for the heads up

**Comment by fizzxed** [comment]
Np, hopefully you change all accounts that use those credentials

**Comment by BrianEstrada** [comment]
ahaha first thing I did! Someone tried to access my facebook -_- btw idk if you're on the subreddit but the alpha version is out for testing if you're interested
