### ISSUE TITLE
update java api to latest dev branch

### ISSUE THREAD

**Issue by Tsunamii** [BrianEstrada/PokeScanner#145]
https://github.com/Grover-c13/PokeGOAPI-Java/issues/293
GoogleAutoCredentialProvider makes the login much easier :)

**Comment by john086** [comment]
I can use signin button of google play services ?

**Comment by BrianEstrada** [comment]
Still trying to figure out the new API might take a little longer than expected

**Comment by BrianEstrada** [comment]
Current branch is not working with android (uses java 8)

**Comment by BrianEstrada** [comment]
Newest API has been implemented in 1.7.6
