### ISSUE TITLE
Add Server Down Notification to Maps

### ISSUE THREAD

**Issue by BrianEstrada** [BrianEstrada/PokeScanner#148]
Current there is no display for users to know when the server is down so we need to work on that

**Comment by Hoully111** [comment]
Great idea :)

**Comment by BrianEstrada** [comment]
Implemented in 1.8.0

**Comment by Hoully111** [comment]
Where is 1.8.0 available

**Comment by BrianEstrada** [comment]
Check the subreddit its stickied
