### ISSUE TITLE
The scanning function stops working after several scans

### ISSUE THREAD

**Issue by tienduccao** [BrianEstrada/PokeScanner#149]
I scanned on 3 different locations on the map.
When I tried the 4th scan, there's no progress on the scan button and I saw no pokemon.

**Comment by BrianEstrada** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/issues/325

It's an issue with the JAVA API going to be fixing this later

**Comment by tienduccao** [comment]
I think it's better if we show some notifications to user

**Comment by BrianEstrada** [comment]
Issue has been fixed in 1.7.6
