### ISSUE TITLE
Keep asking to Enable Location Service

### ISSUE THREAD

**Issue by cepoterbang** [BrianEstrada/PokeScanner#150]
Hello.. 
After update to version 1.7.1 when I try to run my scanner keep asking me to Enable Location Service to Continue... It never occured in all previous version... 
I'm using Nox App Player... Thx

**Comment by InstallGentoo11** [comment]
Same here. It shouldn't demand it anyway considering you could scan without the gps on.

**Comment by BrianEstrada** [comment]
yeah it's being removed in 1.7.2 sorry about that guys

**Comment by InstallGentoo11** [comment]
You shouldn't have removed the old versions, so people can actually download them and use them.

**Comment by BrianEstrada** [comment]
@InstallGentoo11 Our API keys were released publicly we had no choice but to remove the keys.
