### ISSUE TITLE
why  every time i use the pokemon scanner msp does not appear?

### ISSUE THREAD

**Issue by teioh007** [BrianEstrada/PokeScanner#151]

**Comment by BrianEstrada** [comment]
What version are you using? anything pre 1.5.0 isnt gonna work.

**Comment by teioh007** [comment]
first I used the pokemon scanner 1.5.2 can be used. after i finished doing
flash my smart phone. I reinstall the pokemon scanner 1.5.2. when I use it
again suddenly the map gps does not appear. do you have solution for this
problem?
Pada tanggal 29 Jul 2016 12.08 PM, "Brian Estrada" <notifications@github.com>
menulis:

**Comment by BrianEstrada** [comment]
Update to 1.7.0
