### ISSUE TITLE
Pokemon Blacklist

### ISSUE THREAD

**Issue by Hoully111** [BrianEstrada/PokeScanner#152]
I like the select Select All and None feature but anyway to move them up top and bring back the save button down bottom 3 times now i clicked None :(

**Comment by BrianEstrada** [comment]
lmaooo I keep doing the same thing I'll see what I can do.

**Comment by Hoully111** [comment]
Well you know it's bad if your doing it hahahah jk still an excellent feature just bad location :)

**Comment by BrianEstrada** [comment]
[How does this look?](https://dl.dropboxusercontent.com/u/31949989/Capture.PNG)

**Comment by Hoully111** [comment]
Perfect but will we have a save button dowk bottom or just back button on your phone either way works in my opinion

**Comment by BrianEstrada** [comment]
I could add a back button but the save button is redundant and confuses people because the list automatically saves after being checked

**Comment by Hoully111** [comment]
Ok true just aslong as the back button isnt up top hahaha

**Comment by BrianEstrada** [comment]
Issue marked as fixed
