### ISSUE TITLE
No map mode

### ISSUE THREAD

**Issue by MajorNewbie** [BrianEstrada/PokeScanner#153]
Awesome app! Would it be possible to have a mapless mode that either didn't load the background google maps or showed direction/rough position to the pokemon (even if only in list format). This would save on map data as well as keeping some of the mystery/fun in having to discover pokemon.

**Comment by BrianEstrada** [comment]
hmmmm sounds like listmode?

**Comment by BrianEstrada** [comment]
We could add something like that in the future where it just scans cordinates and outputs a list

**Comment by MajorNewbie** [comment]
Originally I was more thinking just as it is but without the maps, so more like a 'radar' with a circle showing scan area and then the pokemon inside that circle, perhaps with smaller circles denoting distance (100m, 200m lines, etc) but figured depending on how the map integration is, that might end up being an entirely separate app/interface, hence the list idea.

However, to be useful, the list would probably need more GPS/Geocache type features, so working out direction based on phone's orientation, rough guide to distance, etc... again this is starting to sound like a separate interface/app.

Either way, on reflection seems well out of scope. If the offline caching of google maps is utilized by PokeScanner, that in itself seems like a 'fix'. I just don't know if it can utilize that data or requests mapping data itself.

Anyhow, great app, awesome work.

**Comment by MajorNewbie** [comment]
Just saw the list view, great work! Would it be difficult to add a heading/compass direction? I'm probably over thinking, it doesn't need to update, you can just re-scan.

**Comment by InstallGentoo11** [comment]
There is something I wanted to suggest myself so I will use this thread to do. I have heard, I have no idea if it is correct, that if you have downloaded for offline usage the map of let's say your city in google maps the game won't use your mobile data to load it, but that offline download (for my city was like 40mb, it is not much). I wonder if this could be done with this app.

And for gods sake, let it remember your last scan location or start with the city of your last scan or something like that. Don't start with the world map every time. You could even have an option about it or something so it would be optional.

**Comment by BrianEstrada** [comment]
@InstallGentoo11 should probly create a new thread

**Comment by StephanBijzitter** [comment]
You can also download your region from the Google Maps app and use it offline, which also saves a lot of data.

**Comment by BrianEstrada** [comment]
Implemented in the latest version! Expect to see No map mode in 1.8.0 alpha 003!
