### ISSUE TITLE
Automatic updator doesn't trigger installation after downloading

### ISSUE THREAD

**Issue by jaydlawrence** [BrianEstrada/PokeScanner#159]
I am not sure if this is an issue or not, since I don't know how the updater is intended to work.

I have tried using a few times. Each time it downloads the file and then the file doesn't trigger an auto install. I have to go looking for it to trigger the install.

It took ages to download over mobile data, so it could be that while waiting I closed the app or went to the lock screen.

How is it supposed to work?

Is it going to be put on the play store at some point? That takes care of the updating for you right?

**Comment by kurasa** [comment]
i'm agree with jaydlawrence ... i found error after update n downloads

**Comment by BrianEstrada** [comment]
We're looking at possible publishing on the playstore

**Comment by BrianEstrada** [comment]
Should be fixed in 1.7.6
