### ISSUE TITLE
[Suggestion] Please show scanned locations

### ISSUE THREAD

**Issue by dwk001** [BrianEstrada/PokeScanner#160]
As the map is scanning locations, it is my understanding that this app is jumping from location to location, scanning. Can you show where the map is currently scanning? [Like this](https://gfycat.com/ShortFinishedDinosaur) It would be nice to know where the app is currently scanning.

**Comment by BrianEstrada** [comment]
This has been implemented in the latest push

**Comment by BrianEstrada** [comment]
Expect it 1.8.0

**Comment by dwk001** [comment]
How can I get into the alpha?

**Comment by j0be** [comment]
https://www.reddit.com/r/PokeScanner/comments/4vmai5/v180_alpha_build_002/
