### ISSUE TITLE
API-Changes: Scanner isn't working proper anymore

### ISSUE THREAD

**Issue by starfo** [BrianEstrada/PokeScanner#161]
It seems as if the returned radius is now only 70m instead of 100m:

https://www.reddit.com/r/pokemongodev/comments/4v73aj/psa_scan_radius_was_changed_from_100m_to_70m/

**Comment by starfo** [comment]
Only this line needs to be changed, right? https://github.com/BrianEstrada/PokeScanner/blob/master/app/src/main/java/com/pokescanner/helper/Generation.java#L55

An probably also the text in the menu: higher_number_slower_search

**Comment by BrianEstrada** [comment]
Thanks It's been changed!

**Comment by starfo** [comment]
@BrianEstrada I think now it is to small. Shouldn't it be 140 instead of 70? The 200 was the distance between scan positions and therefore 200 was 2*radius.
