### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by fonix232** [BrianEstrada/PokeScanner#162]
I see you've taken code development to a different place.

Since the original work was licensed under GNU GPL v3, unfortunately you cannot make the code private - it requires you to make sure anyone who can get the binary version (i.e. the APK) can receive the source code that was used to build it.

Since you're pushing updates through Fabric's Beta, many will have the right to request the source code. I highly suggest removing the GPL-breaking note from the README - even though you are the creator, you can't decide to suddenly license it under a more restrictive set of rules. It is against the original license.

I understand the issue with rebranding and selling your hard work. It comes with GPL. Anyone can repackage, rename, and sell your product as their own. The most famous case of such thing happening is Blender - the open-source, free, GPL-covered 3D editing software. [See here](https://www.blender.org/press/re-branding-blender/).

I can also understand your frustration. However Google is VERY keen on licensing of things on the Play Store. Send them an e-mail regarding the licensing issue, and they will take the offending apps down (however I'm pretty sure that soon all versions of your code will be taken down as it breaks the ToS of Pokemon GO). As for the users who buy it - it is sad, but you can't do anything more.

I would really like to see this project go forward, but unfortunately your current path practically breaks the very license you chose to roll with in the first place.

**Comment by BrianEstrada** [comment]
I understand what you are saying but we are currently still deciding what to do...

GPL does allow you to take a REPO private but you must provide the source when request and you are allowed to charge for that source..

https://www.gnu.org/licenses/gpl-faq.en.html#DoesTheGPLAllowMoney

which is something we are exploring...Currently the situation is not okay devs are profiting from our hard work without putting in any themselves, they are literally just forking the project and throwing it up on google play and charging money...we would rather our hard work not be sold, and if it is sold that we a least make something from it.

**Comment by fonix232** [comment]
You can take the repo private. My problem wasn't with that. It was with the second half of the statement, namely, that you will only allow access to the code to people who've already committed to the project themselves.

I understand the situation is not okay. However, due to the licensing, you can't do much. You can't make sure that only people who will respect your work will get the source code. You have to provide it to ANYONE who has a claim (i.e. has access to a binary version of that source code, in this case, an APK). WE can get into lengthy legal fights, but basically what you try to fight against is allowed by the license you chose.

So far, only the guys who redistribute without copyright notice, etc., are the bad guys. You can step up to them in a legal manner. You can make sure their apps are taken down due to the licensing issue. However you cannot break GPL itself, because in that case the whole license is invalidated, and you, the creator, lose all rights to your own work.

Unfortunately, GPL won't let you restrict the use of the source code. Also, what you're quoting... 

"**Does the GPL allow me to charge a fee for downloading the program from my distribution site?**
Yes. You can charge any fee you wish for distributing a copy of the program. If you distribute binaries by download, you must provide “equivalent access” to download the source—therefore, the fee to download source may not be greater than the fee to download the binary."

Since you're making the binary available for free, you can't charge a dime for the source. So unless you want to sell the APK itself, you cannot sell the source code (well you can, but you must provide it free of charge to anyone who asks for it and points at the license).

**Comment by gruntlord6** [comment]
"therefore, the fee to download source may not be greater than the fee to download the binary." You have it backwards, it means you cannot charge more for the source then the binary (The source would be available at the same cost).

**Comment by jaydlawrence** [comment]
Along these same lines, I found this paid for version on the Play store that seems to be very similar to yours. Us it a fork? 
Is it legal? 
https://play.google.com/store/apps/details?id=com.pokescannerplus

**Comment by BrianEstrada** [comment]
@jaydlawrence definatley not us it's some guy from Arizona (Same guy has uploaded our app 3 or 4 diff times now) trying to make a quick buck.

**Comment by jaydlawrence** [comment]
Have you guys reported him?
If you guys add yours for free to the play store, hopefully it will
overshadow all the paid for clones?

**Comment by BrianEstrada** [comment]
@jaydlawrence I don't really want to get into any legal trouble with Niantec so we've avoided going onto the AppStore

**Comment by fonix232** [comment]
@gruntlord6 I said exactly the same as you did.

@jaydlawrence unfortunately nothing can be done, except reporting them for license violation. GPL allows the sale of someone else's work.

@BrianEstrada while you don't have to upload to the Play Store, you can still report them for GPL violation (it does explicitly state that ALL previous contributor must be credited).
