### ISSUE TITLE
PokeStop Clusters

### ISSUE THREAD

**Issue by j0be** [BrianEstrada/PokeScanner#163]
Basically, whenever you scan, it grabs the Pokéstop data. With every stop it finds, I want to have it check the scanner radius length {edit: 40m} around that stop for other stops. If the number of reachable stops from a single point exceeds the user defined threshold (default 3) it will add a map entry for the Pokéstop cluster.
This would be immensely useful in cities to find great locations to stock up on items.

**Comment by j0be** [comment]
Feel free to assign this to me

**Comment by BrianEstrada** [comment]
I'm going to work on this but It's going to be a while just because the way markers are displayed right now needs to be reworked into one class (spread upon 3)

**Comment by BrianEstrada** [comment]
#21

**Comment by j0be** [comment]
Haha, well, I actually was meaning a method to find stops that are all within scanning range in game. Basically locations that have high density of pokemon stops, but yeah, display too. :P
