### ISSUE TITLE
suggestion: ability to login with multiple id

### ISSUE THREAD

**Issue by ferlynlie** [BrianEstrada/PokeScanner#164]
I wonder if the feature of multiple id do the scan with certain distances set by user. It will do the faster scanning process with the wider results. Hahaha. Thanks man.

**Comment by fonix232** [comment]
Totally unnecessary. Scanning won't be faster because of that.

**Comment by BrianEstrada** [comment]
Has been implemented in 1.8.0 check out the alpha for a preview :)
