### ISSUE TITLE
How to random Google API Key?

### ISSUE THREAD

**Issue by kurasa** [BrianEstrada/PokeScanner#165]
Great apps.... 
if I may give a bit of feedback, whether it is possible to add google API KEY more and configured in a random? because of limited API

**Comment by BrianEstrada** [comment]
Android Google Maps API has no limit.

**Comment by kurasa** [comment]
How about this?
https://developers.google.com/maps/faq?csw=1#usagelimits

because I use the free API

Thanks for advance

**Comment by BrianEstrada** [comment]
http://i.imgur.com/TczUqxM.png
