### ISSUE TITLE
Can no longer use Google ID with 2FA after update

### ISSUE THREAD

**Issue by modoj** [BrianEstrada/PokeScanner#166]
It appears the app was changed to use Google credentials directly rather than accessing device accounts, though it seems I cannot use my account now as it replies as bad credentials rather than prompting for 2fa code.

**Comment by BrianEstrada** [comment]
I wanna say you shouldn't be using an account with 2FA and you definately shouldn't be using your main account...create a throw away account because there is a chance your main account will be banned lol.
