### ISSUE TITLE
Driving Radius

### ISSUE THREAD

**Issue by Hoully111** [BrianEstrada/PokeScanner#168]
Idk if this is even possible depending on how the search radius feature works but would it be possible to have the search radious we designated follow us LIVE as we drive...hope that makes sense

**Comment by BrianEstrada** [comment]
This should be Driving Mode it won't update quickly unless you turn up the map refresh other than that I'm not 100% sure what you're talking about.

**Comment by j0be** [comment]
@BrianEstrada, it is there already.
