### ISSUE TITLE
Login / last update

### ISSUE THREAD

**Issue by lightnshine1** [BrianEstrada/PokeScanner#169]
Since last update no login possible with multiple gmail/google accounts.  Works  fine with PTC account but i pref google acc.  Error is always "wrong login" :/. Thx 4 this great  app btw.

**Comment by BrianEstrada** [comment]
Do your accounts have two factor authenthication?

**Comment by lightnshine1** [comment]
Yes i think so, need to check it. Do i have to turn it off? Thx for the fast reply.

**Comment by BrianEstrada** [comment]
Yeah it wont work with two factor anymore you should avoid using a real
account for this use a throw away

**Comment by lightnshine1** [comment]
Ok well created another account and works fine now. But the one i used was also not my main  account. Thanks for the help anywayzzz :).
