### ISSUE TITLE
Pokemon not showing up on scanner

### ISSUE THREAD

**Issue by X3N0F00B** [BrianEstrada/PokeScanner#170]
https://goo.gl/maps/2zSKnLZBKeD2

At this spot a pokemon spawns at 6 mins before every hour and it stays there for an hour. Those pokemon never show up in pokescanner, how is this possible?

**Comment by BrianEstrada** [comment]
I don't get any results there either...neither does pokevision sooo?

**Comment by JudasRebel** [comment]
Same on me. No pokemons appear on this map. I tried all setting but still no appears.

**Comment by JudasRebel** [comment]
Version before was pretty cool, everithing is fine. But suddenly, the map is gone. Pokemons show up, map hidden. Then I trying this version. No Pokemon.

**Comment by X3N0F00B** [comment]
I got results on scans but not the one on the spot I pointed out. I checked the spot several times on several versions but the Pokémon on that spot won't show

**Comment by ElySoul** [comment]
after the upgrade, the scanner began to show a much smaller pokémon, this problem will be solved?

I apologize for my English translated through the translator

**Comment by BrianEstrada** [comment]
@ElySoul yes this should be solved in 1.8.0
