### ISSUE TITLE
Servers Not Responding

### ISSUE THREAD

**Issue by Hoully111** [BrianEstrada/PokeScanner#172]
Servers Not Responding but ispokemongodowm sais everything is fine

**Comment by Hoully111** [comment]
Went back to 1.7.3 works

**Comment by BrianEstrada** [comment]
PTC or Google?

**Comment by Hoully111** [comment]
Google

1.7.3 is working fine

**Comment by MarcQA** [comment]
Can't log in using a Google account :(

**Comment by Hoully111** [comment]
Any update

**Comment by BrianEstrada** [comment]
Someday...eveenntuualllyyyyy I don't really like pushing updates without testing them so it might be a lil while.

**Comment by Hoully111** [comment]
Fair enough just didn't know if the issue waa discovered

**Comment by BrianEstrada** [comment]
ah yeah the issue is fixed in 1.7.5 It's finished I just neeeed some testing...feel like testing @Hoully111 ?

**Comment by Hoully111** [comment]
Sure

**Comment by BrianEstrada** [comment]
email me lovesguitar@gmail.com

**Comment by antibomb** [comment]
stopped working entirely a little while ago.  upon taking the OTA auto-update to 1.7.5 its working much, much better.  just some additional evidence to what you likely already know.

**Comment by BrianEstrada** [comment]
@antibomb thanks for the info
