### ISSUE TITLE
Says scan canceled

### ISSUE THREAD

**Issue by dusktildawn48** [BrianEstrada/PokeScanner#175]
when i start it up it takes me to the map but says bad login credentials. then if i try to start a scan it says scan canceled.

**Comment by dusktildawn48** [comment]
nvm im an idiot.

**Comment by antibomb** [comment]
did you update to latest version? 1.7.5 working well on my end

**Comment by dusktildawn48** [comment]
yeah, it also says servers not responding too. restarted my phone, same thing.

**Comment by dusktildawn48** [comment]
is ptc having issues? may be working correctly on gmail account
