### ISSUE TITLE
Permissions explanations

### ISSUE THREAD

**Issue by ericwooley** [BrianEstrada/PokeScanner#177]
My wife won't install the app until she knows why it wants to have access to media.

I know it's FOSS, but it is always nice to know.

Great app by the way! We love it (on my phone)

**Comment by BrianEstrada** [comment]
Ahaha it's for the auto updater you can always deny the permission on marshmellow it has no affect on the phone!

**Comment by ericwooley** [comment]
That was quick! Thanks man! Should I close the issue?
