### ISSUE TITLE
Please make a web version of this or put it on the app store

### ISSUE THREAD

**Issue by FlamingObsidian** [BrianEstrada/PokeScanner#179]
On my Kindle Fire it's hard to install APKs. I would appreciate it if you did this request.

**Comment by jake9000** [comment]
I can get why the dev wouldn't want to upload to the play store (kinda a grey area app, and account penalties from Google can be devastating).

But an F-droid upload would be rad.

**Comment by BrianEstrada** [comment]
@jake9000  I've looked up how to submit there but I'm still not 100% sure :(

**Comment by BrianEstrada** [comment]
@FlamingObsidian [Installation Instructions](http://www.technipages.com/kindle-fire-how-to-install-apk-files)
