### ISSUE TITLE
Get Directions

### ISSUE THREAD

**Issue by SpiderDice** [BrianEstrada/PokeScanner#18]
Would be a great feature in a future build. Simple navigation to the Pokémon.

**Comment by Schism169** [comment]
Agreed! Would love it if you could click on the Pokémon and have an option to open Google maps to drive there!

**Comment by BrianEstrada** [comment]
It was in the previous version not sure why it's not there anymore I'll look into it.

**Comment by ubergeek77** [comment]
It would be nice to include this functionality in the white bubble that pops up when you click on something. And actually, that bubble gets cleared on map refresh, sometimes that's every 1-2s. I was thinking about making an issue for it, but hopefully you/some other dev reads this and it's easily addressable.

**Comment by BrianEstrada** [comment]
The issue has been fixed! Navigation should be back in the app :)
