### ISSUE TITLE
Scan range and scan delay need to be adjusted.

### ISSUE THREAD

**Issue by petteri72** [BrianEstrada/PokeScanner#180]
Poke scanner currently shows only few pokemons, probably because it has too wide scan radius (Ninantic changed players heartbeat from 100m to 70m) and too low scan delay (there could also have been been change in scan delay for rare pokemons.) .

Pokemon Go Map shows everything if scan radius is tight and scan delay long. Of course this  Is it possible to add heartbeat and scan delay fields to options so that they can be adjusted?

**Comment by BrianEstrada** [comment]
There are two settings in the app that have been there since 1.3...
