### ISSUE TITLE
Pokemons disappear from map on screen rotate

### ISSUE THREAD

**Issue by jehy** [BrianEstrada/PokeScanner#184]
version 1.7.6 hides all pokemon when rotating screen. Also, "scan" button becomes active once again, you can press it and it launches two scanning processes simultaneously.
Possible fix - force portrait orientation.

**Comment by BrianEstrada** [comment]
Some users are using tablets and this is something that can be fixed on the users side by locking rotation

**Comment by jehy** [comment]
Why close the bug? If you rotate the screen on tablet, application misbehaves... Just choose another fix :)
