### ISSUE TITLE
Adding option to change Pokemon Server

### ISSUE THREAD

**Issue by JudasRebel** [BrianEstrada/PokeScanner#187]
I have small problem and high ping to acces US and EU server. Because I play preofficial pokemon in my country in Asia Pasific. 
Can we change to Australia server or Japan server while we using Pokescan apps?
Thanks before. :)

**Comment by rhari991** [comment]
This is not possible on our end, it is Niantec who decides which server to connect to. It seems it does not pick using regional preferences.
