### ISSUE TITLE
Use multiple accounts to boost scan performance (why was scan performance reduced?)

### ISSUE THREAD

**Issue by robert862** [BrianEstrada/PokeScanner#189]
Using 2 or even more accounts in parallel would increase the speed of scan.
and why was the scan delay increased in 1.7.6?

Using the old version I need about 8 Minutes to scan a radius of 1 mile. If it is even more now, most pokemon will be gone by the end of the scan, as the last for about 10-15 minutes?!

**Comment by BrianEstrada** [comment]
This is already a feature in 1.8.0 check the beta thread on reddit.
