### ISSUE TITLE
[Suggestion] Multiple account support

### ISSUE THREAD

**Issue by Lionir** [BrianEstrada/PokeScanner#192]
Having multiple accounts to scan an area would make scanning much faster than it's current state while still respecting the 5-5.5seconds delay imposed by the server. This would be great if it could be implemented. Thank you for the amazing work.

**Comment by rhari991** [comment]
This has been implemented in in the v1.8 alpha. You can try it out from the subreddit.

**Comment by Lionir** [comment]
@rhari991 Oh, It should be published here too. It'd be accessible to more people.

**Comment by j0be** [comment]
https://www.reddit.com/r/PokeScanner/comments/4vmai5/v180_alpha_build_002/

Since it isn't an official release yet, it will not show in the list of  releases.

**Comment by Lionir** [comment]
@j0be I think Betas and Alpha apks should also be published here to make it easier to find them from a trusted source.
