### ISSUE TITLE
[Question] Major Lag

### ISSUE THREAD

**Issue by Lionir** [BrianEstrada/PokeScanner#194]
Scanning New York is nearly impossible due to immense lag and I have a fairly new device (LG G3). Would it be possible to have an option to replace all picture with lower resolution ones and save all images into cache to make it slightly faster? I'm not sure how exactly we'd be able to make lag as minimal as possible while showing all the information needed. I think that hiding the time left before disappear could also help..

**Comment by Lionir** [comment]
Also, why does it look for Pokestops much farther than the scanned area?

**Comment by BrianEstrada** [comment]
Lionir that's just how the API works, look at the game you can see gyms much further than you can see pokemons. I'd rcommend disabling Gyms and Pokestops if you are having lag. And you can down size the pokemon icons.

The issue is with the Google Maps API doesn't like having multiple markers.

**Comment by Lionir** [comment]
@BrianEstrada Could there be an option to not show Pokestops/Gyms which are outside of the scanning since they create a lot of markers therefore creating lag for absolutely no reason? Downsizing the icon would just make the marker look smaller from what I know and I've already set it as small as I can due to personal preferences.

**Comment by BrianEstrada** [comment]
@Lionir Currently right now it's only rendering whats in your view so zooming in should help with whatever lag you're having I suggest using filters to see what pokemon you want to see other than that there is no real solution to this other than Implementing Clusters (Which is planned)

**Comment by Lionir** [comment]
@BrianEstrada What would implementing Clusters do?

**Comment by BrianEstrada** [comment]
Less Objects -> Less Lag

Read up here it isn't an issue with our app unfortunately.

http://stackoverflow.com/questions/13713066/google-maps-android-api-v2-very-slow-when-adding-lots-of-markers
