### ISSUE TITLE
Scan Rare  pokemons problem

### ISSUE THREAD

**Issue by nivlacc** [BrianEstrada/PokeScanner#195]
Before the pokemon go updated i can scan a lot of rare pokemons around my house  (at least 1-2hours has one )

after the update i spend whole day to scan the rare pokemons, but it doesn't  show anything (maybe 8 hours has one rare pokemon)

when i scan common  pokemons it works

do u know whats going  on ?    are they decrease the rare pokemons spawn rate?

**Comment by StephanBijzitter** [comment]
Niantic has modified a lot of spawns.

In my own city, there's also significantly less rare/very rare pokemon. It's just how it is...

**Comment by j0be** [comment]
Sadly, @StephanBijzitter is right. I had been planning on going out to my local Lickitung spawn, but then the update happened. :/
