### ISSUE TITLE
can't see any pokemon

### ISSUE THREAD

**Issue by cadaxx** [BrianEstrada/PokeScanner#196]
Hello, someone have the same problem? I have no pokmon on my map, i scanned many times in different locations but its still the same stuff. Pls help me :D

**Comment by BrianEstrada** [comment]
sorry this is the wrong place for support. If you're looking for help check out this thread.

https://www.reddit.com/r/PokeScanner/comments/4vrdon/help_thread_commonly_asked_questions/
