### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by neutron666** [BrianEstrada/PokeScanner#198]
Please add support for multiple ptc accounts. Let each account have a own Thread. This would dramatically increase scanning speed.

**Comment by BrowncoatShadow** [comment]
This is already in the 1.8.0 alpha; see the [thread](https://www.reddit.com/r/PokeScanner/comments/4vmai5/v180_alpha_build_002/) on the sub.

However, on the subject of multiple accounts, in 1.8.0, we currently have to enter each account in manually (username and password). It would be great if we could import en masse with something like:

```
user129583:pass489724
user037563:pass927371
user473929:pass729285
...
```

This would allow us to easily import multiple accounts, without manually entry or copy/pasting usernames and passwords.

**Comment by Farigh** [comment]
Would be great to be able to add google accounts to the manager, PTC login is often down

**Comment by BrowncoatShadow** [comment]
@Farigh The problem with using multiple google accounts for multiboxing is the authorizations only last 30 minutes, meaning you would have to sign in to each account again every half hour.

**Comment by BrianEstrada** [comment]
Closing this because it is already in 1.8.0
