### ISSUE TITLE
scan time so long?

### ISSUE THREAD

**Issue by wtfusernametaken** [BrianEstrada/PokeScanner#199]
ist takes like 2 minutes on a level 4 scan and finds about 2 pokemon.

is that really normal? why is it so slow? o.O

oh and sometimes i scan a new area, and it finds some pokemon, then i scan the area again like 2 min later and suddenly it shows a pokemon like eevee with 3 min left or so. why doesnt it appaear on the first scan?

**Comment by rhari991** [comment]
Read the comments on the subreddit
https://www.reddit.com/r/PokeScanner/
before you ask here.
