### ISSUE TITLE
minimum_scan_refresh is now 10s

### ISSUE THREAD

**Issue by ishti10** [BrianEstrada/PokeScanner#201]
We should add a UI option to change minimum scan refresh time per account, to keep up with minimum scan refresh updates

**Comment by j0be** [comment]
Sigh. :'(

https://www.reddit.com/r/pokemongodev/comments/4vuijn/psa_minimum_scan_refresh_now_10s/

**Comment by j0be** [comment]
It's easy to update this to 10 seconds, but I'll look into a more foolproof method of obtaining the delay time.

**Comment by BrianEstrada** [comment]
@j0be sounds good :+1:  :)
