### ISSUE TITLE
[Suggestion] Circle identified by accounts.

### ISSUE THREAD

**Issue by Lionir** [BrianEstrada/PokeScanner#203]
The ability to see which circle is being scanned by which account. This would make account troubleshooting much easier.

**Comment by chilimanjaro** [comment]
Different color instead of read randomly assigned to each account would be easy to distinguish.

**Comment by Delloman** [comment]
Account number on each circle

**Comment by Lionir** [comment]
@BrianEstrada Delloman's idea sounds better than using colors.

**Comment by BrianEstrada** [comment]
@Delloman it's a good idea it just isn't feasible to implement, we would have to take the marker turn it into a bitmap or canvas and draw a number over it (which is CPU intensive at least for older devices)

**Comment by Delloman** [comment]
To bad  it  would make trouble shooting easy

**Comment by Lionir** [comment]
@BrianEstrada Could there be an option in the settings which allow to use numbers instead of colors to identify accounts?
