### ISSUE TITLE
Distance to pokemon

### ISSUE THREAD

**Issue by ecl1ps** [BrianEstrada/PokeScanner#205]
I would like to propose new feature.

It would be nice to see a distance to pokemon. It is sometimes quite difficult to judge it just from map. Pokemon details tooltip could be the right place. And maybe somehow distinguish pokemon in visible range (70m).

Thanks

**Comment by BrianEstrada** [comment]
I don't think we'll be adding any more graphics to the main maps area due to the fact that it's already killing lowerend devices and even higher end devices If you want to see range Listmode has range and the newest version of Listmode (alpha 003 not out yet) has improved upon that feature.

**Comment by ecl1ps** [comment]
Well, not on main map. By "pokemon tooltip" I was referring to popup box which shows when you click on pokemon icon on map. That way you wouldn't be adding more elements to map.

Distinguishing visible pokemon on map is another thing. My first idea was to change pokemon "time left" background color to green (or something). You are already doing it for lured pokemon (purple). It wouldn't add anything new for rendering either.

What do you think? I _might_ look into it but I won't be able to for at least a week.
