### ISSUE TITLE
Expiration timer has 30min added to it.

### ISSUE THREAD

**Issue by jatinhariani** [BrianEstrada/PokeScanner#207]
On the map, timers show up with values between 30:00-45:00. Pokemon expire and disappear at 30:00.

**Comment by BrianEstrada** [comment]
This has been fixed in 1.8.0 Alpha 003

**Comment by rhari991** [comment]
nice to see another indian here :)

**Comment by jatinhariani** [comment]
Built the latest source code. Can confirm that this has been fixed. Thanks.
