### ISSUE TITLE
+30m bug still present on lured pokemon

### ISSUE THREAD

**Issue by jatinhariani** [BrianEstrada/PokeScanner#212]
Lured pokemon still spawn at 33:00 and disappear at 30:00.
Normal pokemon seem proper.
Using app built from source.

**Comment by jatinhariani** [comment]
Could look into it myself if you point out the commit that did the fix for other pokemons

**Comment by BrianEstrada** [comment]
It's okay It's a single line fix I'll be uploading it shortly
