### ISSUE TITLE
Ring Guide Disappeared

### ISSUE THREAD

**Issue by andibuch** [BrianEstrada/PokeScanner#216]
Wanted to call this to your attention too:

In the latest build I played with earlier today, the ring that would appear around the center of your screen as a guide to the area that will be searched once the search was initiated was gone

This made it very difficult to figure out reliably what area I would be scanning before clicking the scan button.

Granted, it would appear (as a hexagon) once pressed, but it's extremely helpful to have a guide before the button is pressed so that you can figure out where to position the scanner pre-scan

I couldn't get it to show up, regardless of what setting the "Show Range" was set to, so I went back to 1.8.0 Alpha Build 2

**Comment by MWin123** [comment]
I have the same problem with an earlier build. See #208 

I'll build the latest one and check again.
