### ISSUE TITLE
Hamburger does not respond to input

### ISSUE THREAD

**Issue by StephanBijzitter** [BrianEstrada/PokeScanner#25]
Using Huawei Ascend Y530
http://www.gsmarena.com/huawei_ascend_y530-6103.php

I can tap on it all I want, or even hold it, but there is no visual indication that anything is happening or going to happen.

The GPS button (with the target icon), does however respond correctly and also shows the shade of grey when tapping on it, which is not the case for the hamburger icon.

**Comment by StephanBijzitter** [comment]
After more testing, it seems input actually passes through the button.

After lining up a Pokémon to be underneath the button, to then press on the button will bring up the name of the Pokémon, as if the Pokémon has been tapped on.

**Comment by BrianEstrada** [comment]
It's not implemented yet it's already in v1.4.0 it''ll be out by tonight :)
