### ISSUE TITLE
Time Limits

### ISSUE THREAD

**Issue by jnovack** [BrianEstrada/PokeScanner#3]
Ideas:

* Under 1minute = Transparency 25%
* Under 3mins = Transparency 50%

Each object needs to have it's own counter, and needs to disappear when the counter is up.

I'd PREFER the counter to be auto-countdown underneath the object.  PokeVision set the bar high on that and anything less is uncivilized.

![](http://techraptor.net/wp-content/uploads/2016/07/pokevision-pokemon-go-niantic.jpg)

**Comment by BrianEstrada** [comment]
lol I'll do my best to add this in

**Comment by BrianEstrada** [comment]
Has been added!

**Comment by jnovack** [comment]
You best is good enough! :)
