### ISSUE TITLE
Menu button not working

### ISSUE THREAD

**Issue by Seguro19** [BrianEstrada/PokeScanner#34]
The left top button for menu is not working or is only my mobile problem?

**Comment by swhittaker** [comment]
Works ok for me, what mobile are you using?

**Comment by Seguro19** [comment]
Xperia Z5 with android 6.0.1

**Comment by swhittaker** [comment]
Latest code hasn't made it to releases page yet. Think it's likely it was added since yesterday, so sit tight

**Comment by SpiderDice** [comment]
Doesn't work for me on Note 5 or Nexus 5X

**Comment by BrianEstrada** [comment]
Check the latest version it should be working.
