### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by jnovack** [BrianEstrada/PokeScanner#4]
Ignore options.

I don't need to see [Generic Common Pokemon to my Area], I just need to see the others.  Allow me to select "on/off" for all 151.

**Comment by Tsunamii** [comment]
+1 for this :)
something like a blacklist/whitelist would be cool, or just make a list with all the pokemon each with a checkbox and only the checked ones will be displayed

**Comment by jnovack** [comment]
Newest version of AHAAAAAA has this.  You may need a refresh of his code-base. it's changed SIGNIFICANTLY.

**Comment by swhittaker** [comment]
It seems that there's a bug with filters here which means scrolling up and down with a filter switched on can sometimes duplicate that filter elsewhere.

**Comment by BrianEstrada** [comment]
@swhittaker Yeah I'm looking into that right now whittaker I'm not really sure whats causing it, it might be an issue with recyclerview, whats your email? I wanna invite you to the slack channel

**Comment by BrianEstrada** [comment]
Has been added!
