### ISSUE TITLE
way to overloaded, nearly crashes

### ISSUE THREAD

**Issue by roflinger** [BrianEstrada/PokeScanner#43]
cool app but the new version is really hard for my phone (xperia z c6603)
i can naerly not use it.
the version of yesterday ( v1.3.0 ) was way more performant

**Comment by BrianEstrada** [comment]
The next version will have the ability to select your refresh rate for the servers! sorry about that

**Comment by roflinger** [comment]
no problem, great project :+1: thank you!

**Comment by BrianEstrada** [comment]
This issue should be fixed in 1.5.0

**Comment by roflinger** [comment]
insane improvement! THX !
