### ISSUE TITLE
Option to cancel scan

### ISSUE THREAD

**Issue by Controless** [BrianEstrada/PokeScanner#5]
Would be nice if there was an option to cancel the current scan in case you need to adjust the scanning area, etc.

**Comment by BrianEstrada** [comment]
I'll add a cancel scan button!

**Comment by Controless** [comment]
Thanks a lot!

**Comment by SpiderDice** [comment]
Great idea!

**Comment by Sigi-cz** [comment]
the CANCEL button in 1.4.1 stays visible after scan is completed
