### ISSUE TITLE
Display lured Pokemon's icons on map

### ISSUE THREAD

**Issue by swhittaker** [BrianEstrada/PokeScanner#50]
Would be useful if lured Pokemon also appeared with icons on the map

**Comment by metherul** [comment]
Please that are spawned via the Lure are only visible to you, so I don't think that'd be possible without using your main account. 

At least I think so. Make sure to tell me if I'm wrong.

**Comment by swhittaker** [comment]
I think that's true for incense, but clicking on the lured pokestops on the map in this app  tells you which Pokemon is currently attracted, but there's no icon for it other than the pink pokestops icon.

**Comment by metherul** [comment]
Ahh, that makes sense. Thanks for the clarification. If Lures "exist" in the same way as Pokemon and Gyms in the API, I don't see why not.

**Comment by BrianEstrada** [comment]
@swhittaker I'll see if I can make a sort of dialog to display which Pokemon are there.
