### ISSUE TITLE
Select All/Clear All for Pokémon Filter

### ISSUE THREAD

**Issue by SpiderDice** [BrianEstrada/PokeScanner#51]
Once I've selected a bunch of Pokémon, and I want to start fresh, it'd be nice to be able to have a "Select All" or "Clear All" button at the top.

**Comment by BrianEstrada** [comment]
It'll be on 1.5.1

**Comment by SpiderDice** [comment]
Awesome!!

**Comment by akshayt23** [comment]
@BrianEstrada I'm on 1.6.3 and couldn't find this option. If you haven't picked it up yet, can I go ahead and start working on it?

Also, I feel the Pokemon filter should be the other way round, ie, check = `show` instead of `hidden`. Let me know your thoughts on this and I'll be happy to fix it and submit a PR.

**Comment by BrianEstrada** [comment]
@akshayt23 I suck and I didn't implemented I'll get around to it  for 1.7.0 promise :(

**Comment by SpiderDice** [comment]
@akshayt23 Yes, I agree. I think that every Pokémon should be selected, is visible.

**Comment by akshayt23** [comment]
@BrianEstrada No issues man. I'll start working on it and create a PR.

**Comment by akshayt23** [comment]
@BrianEstrada Hey I'm done implementing the select all filter. Will raise a PR in some time.

Regarding the issue of the filters being the other way round (ie, `check = show`), there are two ways I can think of to fix that.

1. Change the meaning of a `filtered` Pokemon in the entire codebase. `Filtered` Pokemons would then be considered as those which the user has **selected in the filter** and **wants** to see on the map. Although this method will not be backwards compatible and all old users will see their filters flipped if they update their app.

2. Let the meaning of a `filtered` Pokemon remain as is, ie, a Pokemon which the user has filtered **out** and **does not** want to see on the map. All that's needed then is to reverse the UI logic for rendering the checkbox. This method has the advantage of being backwards compatible but might be a little bit obscure to read as the meaning of `filtered` would be different in the DB and the UI code.

Let me know your thoughts on which method you feel would be a better idea.

**Comment by BrianEstrada** [comment]
The first option should be fine as long as you clear out the sharedprefs file something like
if (firstRun=true) {
sharedprefs.clear; 
firstRun=false;
}

**Comment by akshayt23** [comment]
@BrianEstrada Hey, did you already fix this issue? I was planning to raise a PR containing the **Select All / Clear All** and making **Selected = Hidden** in the Pokemon filter.
