### ISSUE TITLE
Bad login (Servers might be down)

### ISSUE THREAD

**Issue by zanesc** [BrianEstrada/PokeScanner#6]
Just installed v1.2.1 and when i try to sign in i get this error message "Bad login (Servers might be down)". The servers seem to be up and running fine so not sure why. I am running on a Samsung Galaxy S7 on 6.0.1

**Comment by Darkstarlord2** [comment]
Got the same problem

**Comment by LitoOsaka** [comment]
Did you two try to login with a google account? I think the app only support PTC account. I try my PTC and it work fine after many fail attempt with my google acc.

**Comment by zanesc** [comment]
Yup Google account was the issue. Works fine with PTC. Thank you.
