### ISSUE TITLE
Some performance suggestions

### ISSUE THREAD

**Issue by LoungeKatt** [BrianEstrada/PokeScanner#60]
Just passing through and thought I would leave some info if it's of any use.

Multidex is only available in API 21+ (or somewhere around that) and can most likely be eliminated by reducing the overhead associated with Google Play (and possible fabric, which appears to be a means to store personal data and handle transitions, but can appear questionable at first glance)

`<meta-data android:name="com.sec.android.support.multiwindow" android:value="true"/>` is a secondary multiwindow support parameter. Both are valid, but this one will apply to Lollipop devices, such as the Note 4. It is used in conjunction with adding the category `<category android:name="android.intent.category.MULTIWINDOW_LAUNCHER" />` to the desired activity.

While it looks organized, compartmentalizing every item is what leads to massive dex files. It may benefit you (and will benefit the user's RAM) to group things that don't necessarily need an entire class to avoid using a switch or if statement.

Hope it helps. Best of luck.

**Comment by BrianEstrada** [comment]
Thanks for the advice I've been looking into splitting up the classes more and I'll see to adding that meta data to the activities thank you!
