### ISSUE TITLE
Rescanning when moving?

### ISSUE THREAD

**Issue by phantomguy** [BrianEstrada/PokeScanner#69]
Because notification system is coming it will be possible to get notifications when you are on the go (no pun intended). But the problem is the most optimal range to use the notifications is about three steps or LESS. The thing is, this app fixates scanning to the last location where you pressed scan. And if you're on the move you can quickly get out of range and you basically miss important pokemon around you (if they spawn AFTER you leave the area).

So is it possible for the app to refresh scanning if the user gets out of range (as i said, smaller ranges). Like the game basically does. 

It would be great to have something like that.

**Comment by BrianEstrada** [comment]
When the service is added it'll go something like this if you're walking around and the pokemon is within 100 meters you'll get a notification you won't have to constantly click on scan.

**Comment by phantomguy** [comment]
This is great! so i had a genius idea that's already being implemented! awesome. keep up the good work!
