### ISSUE TITLE
List of Pokemons

### ISSUE THREAD

**Issue by Latent1** [BrianEstrada/PokeScanner#70]
Hello,
Maybe will be good idea if you realize the list of Pokemons which will be will be updated when scanning excepting those Pokemons who aren't necessary?

The list in a look an icon + a name + time

The list can be hidden on the right side of the screen, its slice is displayed by a small strip.
By pressing in the list in the field with a name of the Pokemon it is possible to carry out transition to a point on the map where there is a Pokemon. At this time the list moves back to the right side of the screen.
At a dale pressing in the list on a name, can the menu opens - "to hide" and "notify" when finding this Pokemon on the card. Conveniently if a certain type is necessary.
The list can be sorted automatically depending on quality of the Pokemon, the higher it the class, the above is in the list. 
All Pokemons of one class are sorted by group, but in addition in group are sorted by time.
It is possible to issue the notice if the marked-out Pokemon for the notice + the message was found. And also the name of the Pokemon is highlighted on the card and in the list. For convenience.
Thanks.

Example http://i.imgur.com/ZmGUNX1.png

Orig text Russian
Здравствуйте,
Может будет хорошей идеей если вы реализуете список покемонов, который будет обновятся при сканировании исключая тех покемонов которые не нужны?

Список в виде иконка + имя + время

Список можно спрятать с правой стороны экрана, его кусочек отображается небольшой полоской.
При нажатии в списке на поле с именем покемона можно выполнять переход к точке на карте где находится покемон. В это время список задвигается обратно в правую сторону экрана.
При долом нажатии в списке на имени, может открывается меню - "спрятать" и "оповещать" при нахождении данного покемона на карте. Удобно если нужен определенный тип.
Список можно автоматически сортировать в зависимости от качества покемона, чем выше его класс, тем выше в списке находится. 
Все покемоны одного класса сортируются группой, но дополнительно в группе сортируются по времени.
Можно выдавать уведомление если был найден отмеченный покемон для уведомление + сообщение. А так же имя покемона подсвечивается на карте и в списке. Для удобства.
Спасибо.

**Comment by BrianEstrada** [comment]
I'll see to adding this!
