### ISSUE TITLE
Issue upon starting scan

### ISSUE THREAD

**Issue by christiancoleman** [BrianEstrada/PokeScanner#71]
`07-24 18:00:04.041 19430-20860/com.pokescanner E/AndroidRuntime: FATAL EXCEPTION: Thread-18360
                                                                 Process: com.pokescanner, PID: 19430
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.pokescanner.objects.GoogleAuthToken.getId_token()' on a null object reference
                                                                     at com.pokescanner.loaders.MapObjectsLoader.run(MapObjectsLoader.java:91)`

The build on reddit works fine, but the one currently on the repo is crashing upon hitting the search button immediately after login and anytime after the app starts again.

**Comment by christiancoleman** [comment]
Looks like, for whatever reason, it thought I was trying to use a Google account. I commented out those lines, logged out, and relogged using PTC details. It is working now. Not sure if this is something others will experience or not.

**Comment by BrianEstrada** [comment]
@christiancoleman This issue has been fixed in 1.5.2 thanks for reporting!

**Comment by christiancoleman** [comment]
@BrianEstrada Ok sounds great. Is version 1.5.2 _not_ the version currently on Github?

**Comment by BrianEstrada** [comment]
@christiancoleman The current version that is released is 1.5.1 but the one on github is yes 1.5.2

**Comment by christiancoleman** [comment]
Buuuut that's the one I'm using. I compiled it in Android Studio. Same issue :(

**Comment by BrianEstrada** [comment]
ah I haven't update it yet sorry

**Comment by BrianEstrada** [comment]
Check back in about 15 minutes I need to squish some bugs

**Comment by christiancoleman** [comment]
Ahhh ok perfect. Thought I was going crazy for a second. Looking forward to the update!

**Comment by BrianEstrada** [comment]
It should be fixed now :D!

**Comment by Hoully111** [comment]
Is this the issue where you go to click for a new scan but if the app has been idle sometime you have to log out and back in for scan to work??

**Comment by rhari991** [comment]
No, this one causes the app to crash.
If you find a new issue, please create a new issue. Also mention whether you were using a google account or a ptc account
