### ISSUE TITLE
Multi-Language-support for Pokemon names

### ISSUE THREAD

**Issue by robert862** [BrianEstrada/PokeScanner#72]
The UI is already multi-language, but the list of Pokemon shows the English names.
If I knew how to do the translation I would provide the list of German names.

**Comment by EZTEQ** [comment]
This is how we should so it:
https://github.com/AHAAAAAAA/PokemonGo-Map/tree/master/static/locales

**Comment by robert862** [comment]
very good EZTEQ, maybe PScanner can use that list directly.

**Comment by BrianEstrada** [comment]
Implemented
