### ISSUE TITLE
Possible to show IV of the pokemon?

### ISSUE THREAD

**Issue by 2Awesome2** [BrianEstrada/PokeScanner#73]
IV is same regardless of who catches it? (just different seed depending on player's level) Why not show pokemon with a certain IV, or is it not possible?

**Comment by Tsunamii** [comment]
Getting the iv from the pokemon with the java api is already possible. Even for those you already have.
If Brian get's a Pokemon object while scanning it's really easy to implement.

Pokemon.java Line 259++
> public int getIndividualAttack() {
> 		return proto.getIndividualAttack();
> 	}
> 
> 	public int getIndividualDefense() {
> 		return proto.getIndividualDefense();
> 	}
> 
> 	public int getIndividualStamina() {
> 		return proto.getIndividualStamina();
> }

**Comment by ckasek** [comment]
From what I've found poking around in the API code, I don't think this is possible.  The nearby pokemon API just gives you the pokemon ID, encounter ID, lat, long and expiration time.  The Pokemon object is used on the Player side, for seeing what's already in your inventory.

**Comment by BrianEstrada** [comment]
@ckasek Is correct is isn't possible to see the pokemon level closing this
