### ISSUE TITLE
Highlight scanned areas within the circle on the map

### ISSUE THREAD

**Issue by robert862** [BrianEstrada/PokeScanner#76]
It would be great if the parts of the circle, which have already been scanned would be highlighted.
That way the user knows whether there is no (non-filtered) Pin an area or that part of the circle has not been scanned yet.

**Comment by Sigi-cz** [comment]
https://github.com/BrianEstrada/PokeScanner/issues/41

**Comment by EZTEQ** [comment]
Closed as duplicate of #41
