### ISSUE TITLE
New Scan Issue

### ISSUE THREAD

**Issue by Hoully111** [BrianEstrada/PokeScanner#79]
I am having a issue where I go to click for a new scan but if the app has been idle sometime I have to log out and back in for scan to work??

This is using Google Account

**Comment by BrianEstrada** [comment]
ah yeah the token needs to be refreshed every 30 minutes :(

**Comment by Hoully111** [comment]
Not a problem so just log out and back in than all set :)

**Comment by rhari991** [comment]
We could show an error message
Or log them out automatically ?

**Comment by BrianEstrada** [comment]
@rhari991 logging them out automatically would be the best choice

**Comment by Hoully111** [comment]
Or would it be possible to automatically rescan every so often so that the token wouldn't expire? Or is there no way around it expiring

**Comment by BrianEstrada** [comment]
Fixed in 1.5.3v
