### ISSUE TITLE
Pokemon Filter

### ISSUE THREAD

**Issue by Hoully111** [BrianEstrada/PokeScanner#83]
With the latest release this evening the filter isn't working Pokémon i selected to hide in settings are still showing on map

**Comment by BrianEstrada** [comment]
Ahahah you guys are fast

**Comment by Hoully111** [comment]
Not a problem i absolutely love this application i wish i could do more to help

**Comment by rhari991** [comment]
Are they still not hidden when restarting the app ?

**Comment by Hoully111** [comment]
I tried a clean install and no go

**Comment by BrianEstrada** [comment]
I found the bug I'll upload the fix shortly :)

**Comment by Hoully111** [comment]
Thank you for fast support and updates

**Comment by BrianEstrada** [comment]
No problem! This issue has been fixed go redownload the APK and let me know if works for you :)

**Comment by Hoully111** [comment]
All fixed perfect
