### ISSUE TITLE
Revamp the directions and google maps linking

### ISSUE THREAD

**Issue by rhari991** [BrianEstrada/PokeScanner#84]
1) We could open up a dialog when a user clicks on a marker, showing info about the pokemon/gym/pokestop, and add options to show a route right inside our app or to open google maps.

2) Clicking the icons on the bottom right of the map after clicking a marker does not seem to do anything.

3) Add a feature in the setting menu to add all current Gym and Pokestop markers to the Google Maps app.

**Comment by Cynthiachecked** [comment]
Sorry I just double posted, YES this would be great!

**Comment by BrianEstrada** [comment]
This should be implented fully in 1.7.0 Alpha please check the subreddit for the download

**Comment by BrianEstrada** [comment]
https://drive.google.com/open?id=0BwKPMC8uhkNHejFMeFdUT29kcW8 <-Link
