### ISSUE TITLE
Pokemon icons disappearing completely

### ISSUE THREAD

**Issue by bquesse** [BrianEstrada/PokeScanner#86]
On latest apk as of ten minutes ago. Perform a scan and then drag the map view such that the Pokemon are off screen. When you drag the map back to where the Pokemon should be, they are gone. Nexus 6P, Android 6.0.1

**Comment by ubergeek77** [comment]
I had this issue in 1.6.0 too, but I think commit f5b041f fixed it, as it is no longer happening for me after rebuilding. Are you able to build this and confirm for us?

**Comment by BrianEstrada** [comment]
It should be out 1.6.1

**Comment by bquesse** [comment]
Can confirm, thanks!
