### ISSUE TITLE
Icons disappearing/not showing at all

### ISSUE THREAD

**Issue by InstallGentoo11** [BrianEstrada/PokeScanner#89]
I tried today for the first time the app. It was usefully, especially in the beginning, but ended up being far from the smoothest ride. 

It is hard to say how exactly, but it would be something between resizing the map and going between the scanner and the game, the icons of some pokemon or even all just disappear (no, it is not the their timing). Often scans don't even show anything in certain areas and it might be related to not showing pokemon that have already loaded in previous scans, but basically "disappeared" as icons.

Now that I look there are already a few new version so that might have been fixed in them. I downloaded 1.5.3. right before going out. I am on CM12. Don't know if there is anything else I should mention.

Edit: Reading better the release notes it might have been fixed with 1.6.1

**Comment by BrianEstrada** [comment]
Yeah I think this issue was indeed resolved in 1.6.1 :)
